ReservationApp.Web/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Application.Common.Interfaces;
using ReservationApp.Application.Services.interfaces;
using ReservationApp.Domain.Entities;
using ReservationApp.Infrastructure.Data;
using ReservationApp.ViewModels;

namespace ReservationApp.Controllers;

[Authorize]
public class VillaNumberController : Controller
{
    private readonly IVillaService _villaService;
    private readonly IVillaNumberService _villaNumberService;
    public VillaNumberController(IVillaService villaService,
        IVillaNumberService villaNumberService)
    {
        _villaService = villaService;
        _villaNumberService = villaNumberService;
    }
    // GET
    public IActionResult Index()
    {
        var villaNumbers = _villaNumberService.GetAll();
        return View(villaNumbers);
    }

    public IActionResult Create()
    {
        VillaNumbersVM obj = new VillaNumbersVM()
        {
            villas = _villaService.GetAll().Select(u => new SelectListItem
            {
            Text = u.Name,
            Value = u.Id.ToString()
        })
        };
        return View(obj);
    }
    [HttpPost]
    public IActionResult Create(VillaNumbersVM obj)
    {
        if (ModelState.IsValid)
        {
            var res = _villaNumberService.Add(obj.villaNumber, out string errorMessage);
            if (res)
            {
                TempData["Success"] = "Villa number is created successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = errorMessage;
        }
        obj.villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
        );
        return View(obj);
        
    }
    public IActionResult Update(int VillaNumber)
    {
        VillaNumbersVM obj = new VillaNumbersVM()
        {
            villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }),
            villaNumber = _villaNumberService.GetById(VillaNumber)
        };
        return View(obj);
    }
    [HttpPost]
    public IActionResult Update(VillaNumbersVM obj)
    {
        if (ModelState.IsValid)
        {
            _villaNumberService.Update(obj.villaNumber);
            TempData["Success"] = "Villa number is updated successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["Error"] = "Villa number updated failure";
        obj.villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
        );
        return View(obj);
    }
    public IActionResult Delete(int VillaNumber)
    {
        VillaNumbersVM obj = new VillaNumbersVM()
        {
            villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }),
            villaNumber = _villaNumberService.GetById(VillaNumber)
        };
        return View(obj);
    }
    [HttpPost]
    public IActionResult Delete(VillaNumbersVM obj)
    {
        if (_villaNumberService.Delete(obj.villaNumber, out string errorMessage))
        {
            TempData["Success"] = "Villa deleted successfully";
            return RedirectToAction(nameof(Index));
        } 
        TempData["Error"] = errorMessage;
        return RedirectToAction("Error", "Home");
    }
}

ReservationApp.Web/Views/VillaNumber/Create.cshtml
@model VillaNumbersVM
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create VillaNumber</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.villaNumber.VillaId" asp-items="@Model.villas" class="form-control border shadow">
                        <option disabled selected>Select Villa</option>
                    </select>
                    <label asp-for="@Model.villaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.VillaId" class="text-danger"></span>
                    
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.villaNumber.Villa_Number" class="form-control border shadow" />
                    <label asp-for="@Model.villaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.Villa_Number" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.villaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="@Model.villaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.SpecialDetails" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                                <path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/>
                            </svg> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                            </svg> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReservationApp.Web/Views/VillaNumber/Delete.cshtml
@model VillaNumbersVM
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete VillaNumber</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <input asp-for="villaNumber.Villa_Number" hidden/>
                <div class="form-floating py-1 col-12">
                    <select disabled asp-for="@Model.villaNumber.VillaId" asp-items="@Model.villas" class="form-control border shadow">
                        <option disabled selected>Select Villa</option>
                    </select>
                    <label asp-for="@Model.villaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.VillaId" class="text-danger"></span>
                    
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.villaNumber.Villa_Number" class="form-control border shadow" disabled />
                    <label asp-for="@Model.villaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.Villa_Number" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input disabled asp-for="@Model.villaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="@Model.villaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.SpecialDetails" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                            </svg> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                            </svg> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReservationApp.Web/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>
<div class="w-100 card  border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="text-white py-2">Villa numbers</h3>
            </div>
        </div>
    </div>
    <div class="card-body border py-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg> Create Villa
                </a>
            </div>
        </div>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Villa Name</th>
                <th>Villa number</th>
                <th>Special details</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var villa in Model)
            {
                <tr>
                    <td>@villa.Villa.Name</td>
                    <td>@villa.Villa_Number</td>
                    <td>@villa.SpecialDetails</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="VillaNumber" asp-action="Update" asp-route-VillaNumber="@villa.Villa_Number" class="btn btn-warning mx-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                </svg>
                            </a>
                            <a asp-controller="VillaNumber" asp-action="Delete" asp-route-VillaNumber="@villa.Villa_Number" class="btn btn-danger mx-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

ReservationApp.Web/Views/VillaNumber/Update.cshtml
@model VillaNumbersVM
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit VillaNumber</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <input asp-for="villaNumber.Villa_Number" hidden/>
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.villaNumber.VillaId" asp-items="@Model.villas" class="form-control border shadow">
                        <option disabled selected>Select Villa</option>
                    </select>
                    <label asp-for="@Model.villaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.VillaId" class="text-danger"></span>
                    
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.villaNumber.Villa_Number" class="form-control border shadow" disabled />
                    <label asp-for="@Model.villaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.Villa_Number" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.villaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="@Model.villaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="@Model.villaNumber.SpecialDetails" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                                <path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/>
                            </svg> Edit
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                            </svg> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}