ReservationApp.Web/Controllers/CommissionRateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using ReservationApp.Application.Common.utility;
using ReservationApp.Application.Services.interfaces;
using ReservationApp.Domain.Entities;
using ReservationApp.ViewModels;

namespace ReservationApp.Controllers;

public class CommissionRateController : Controller
{
    private readonly IComissionService _comissionService;

    public  CommissionRateController(IComissionService comissionService)
    {
        _comissionService  = comissionService;
    }
    // GET
    public IActionResult Index()
    {
        var commissionRates = _comissionService.GetAll();
        return View(commissionRates);
    }

    [Authorize(Roles = SD.Role_Admin)]
    public IActionResult Create()
    {
        return View();
    }
    [Authorize(Roles = SD.Role_Admin)]
    [HttpPost]
    public IActionResult Create(CommissionRateRequestDTO obj)
    {
        if (ModelState.IsValid)
        {
            var commissionRate = _comissionService.Add(obj);
            TempData["Success"] = $"Commission rate created successfully. Commission rate is {commissionRate.Rate}%";
            return RedirectToAction(nameof(Index));
        }
        return View(obj);
    }
    [Authorize(Roles = SD.Role_Admin)]
    public IActionResult Update(int Id)
    {
        var commissionRate = _comissionService.Get(x=> x.Id == Id);
        return View(commissionRate);
    }
    [Authorize(Roles = SD.Role_Admin)]
    [HttpPost]
    public IActionResult Update(CommissionRate obj)
    {

        if (ModelState.IsValid)
        {
            _comissionService.Update(obj);
            TempData["Success"] = $"{obj.Name} updated, update commission rate successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["Error"] = "Update failure";
        return View(obj);
    }
    public IActionResult Delete(int Id)
    {
        var commissionRate = _comissionService.Get(x=> x.Id == Id);
        return View(commissionRate);
    }
    [Authorize(Roles = SD.Role_Admin)]
    [HttpPost]
    public IActionResult Delete(CommissionRate obj)
    {
        if (ModelState.IsValid)
        {
            _comissionService.Delete(obj);
            TempData["Success"] = $"{obj.Name} updated, update commission rate successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["Error"] = "Delete failure";
        return View(obj);
    }
    #region API
    [HttpGet]
    [AllowAnonymous]
    public IActionResult GetByName(string name)
    {
        var ratePlatformFee = _comissionService.Get(x => x.Name.ToLower() == name.ToLower());
        return Json(ratePlatformFee?.Rate ?? 0);
    }
    #endregion
}

ReservationApp.Web/Views/CommissionRate/Create.cshtml
@model CommissionRateRequestDTO
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create CommissionRate</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input type ="number" step="0.01" asp-for="Rate" class="form-control border shadow" />
                    <label asp-for="Rate" class="ms-2"></label>
                    <span asp-validation-for="Rate" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <!-- icon -->
                            Create
                        </button>

                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="CommissionRate" asp-action="Index" class="btn btn-secondary w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                            </svg> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
        
    </div>
</div>

ReservationApp.Web/Views/CommissionRate/Delete.cshtml
@model CommissionRate
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update CommissionRate</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden/>
            <input asp-for="Name" hidden/>
            <input asp-for="Description" hidden/>
            <input asp-for="Rate" hidden/>
            
            <div class="p-3">
                <div class="form-floating py-1 col-12">
                    <input disabled asp-for="Name" class="form-control border shadow"/>
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input disabled asp-for="Description" class="form-control border shadow"/>
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input type ="number" disabled step="0.01" asp-for="Rate" class="form-control border shadow" />
                    <label asp-for="Rate" class="ms-2"></label>
                    <span asp-validation-for="Rate" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                            </svg> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="CommissionRate" asp-action="Index" class="btn btn-secondary w-100">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                            </svg> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReservationApp.Web/Views/CommissionRate/Index.cshtml
@model IEnumerable<CommissionRate>
<div class="w-100 card  border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="text-white py-2">Commission Rate</h3>
            </div>
        </div>
    </div>
    <div class="card-body border py-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="CommissionRate" asp-action="Create" class="btn btn-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg> Create Commission Rate
                </a>
            </div>
        </div>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Rate</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var commissionRate in Model)
            {
                <tr>
                    <td>@commissionRate.Name</td>
                    <td>@commissionRate.Description</td>
                    <td>@commissionRate.Rate %</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="CommissionRate" asp-action="Update" asp-route-Id="@commissionRate.Id" class="btn btn-warning mx-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                </svg>
                            </a>
                            <a asp-controller="CommissionRate" asp-action="Delete" asp-route-Id="@commissionRate.Id" class="btn btn-danger mx-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

ReservationApp.Web/Views/CommissionRate/Update.cshtml
@model CommissionRate
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update CommissionRate</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden/>
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="All"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow"/>
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow"/>
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input type ="number" step="0.01" asp-for="Rate" class="form-control border shadow" />
                        <label asp-for="Rate" class="ms-2"></label>
                        <span asp-validation-for="Rate" class="text-danger"></span>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                                    <path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/>
                                </svg> Update
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="CommisionRate" asp-action="Index" class="btn btn-secondary w-100">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
                                </svg> Cancel
                            </a>
                        </div>
                </div>
                    </div>
                
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}