ReservationApp.Web/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationApp.Application.Common.Interfaces;
using ReservationApp.Application.Services.interfaces;
using ReservationApp.Domain.Entities;
using ReservationApp.Infrastructure.Data;
using ReservationApp.ViewModels;

namespace ReservationApp.Controllers;

[Authorize(Roles = "Admin,Owner")]
public class AmenityController : Controller
{
    private readonly IVillaService _villaService;
    private readonly IAmenityService _amenityService;
    public AmenityController( IVillaService villaService, IAmenityService amenityService)
    {
        _villaService = villaService;
        _amenityService = amenityService;
    }
    // GET
    public IActionResult Index()
    {
        var Amenities = _amenityService.GetAll(null,"Villa");
        return View(Amenities);
    }

    public IActionResult Create()
    {
        AmenitiesVM obj = new AmenitiesVM()
        {
            villas = _villaService.GetAll().Select(u => new SelectListItem
            {
            Text = u.Name,
            Value = u.Id.ToString()
        })
        };
        return View(obj);
    }
    [HttpPost]
    public IActionResult Create(AmenitiesVM obj)
    {
        if (ModelState.IsValid && _amenityService.Add(obj.Amenity, out string errorMessage))
        {
            
            TempData["Success"] = "Amenity is created successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["Error"] = "Amenity created failure";
        obj.villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
        );
        return View(obj);
    }
    public IActionResult Update(int Id)
    {
        AmenitiesVM obj = new AmenitiesVM()
        {
            villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }),
            Amenity = _amenityService.GetById(Id)
        };
        return View(obj);
    }
    [HttpPost]
    public IActionResult Update(AmenitiesVM obj)
    {
        if (ModelState.IsValid)
        {
           _amenityService.Update(obj.Amenity);
            TempData["Success"] = "Amenity is updated successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["Error"] = "Amenity updated failure";
        obj.villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
        );
        return View(obj);
    }
    public IActionResult Delete(int Id)
    {
        AmenitiesVM obj = new AmenitiesVM()
        {
            villas = _villaService.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }),
            Amenity = _amenityService.GetById(Id)
        };
        return View(obj);
    }
    [HttpPost]
    public IActionResult Delete(AmenitiesVM obj)
    {
        if (_amenityService.Delete(obj.Amenity, out string errorMessage))
        {
            TempData["Success"] = "Villa deleted successfully";
            return RedirectToAction(nameof(Index));
        } 
        TempData["Error"] = errorMessage;
        return RedirectToAction("Error", "Home");
    }
}

ReservationApp.Web/Controllers/BookingController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using ReservationApp.Application.Common.Interfaces;
using ReservationApp.Application.Common.utility;
using ReservationApp.Application.Services.interfaces;
using ReservationApp.Domain.Entities;
using ReservationApp.Hubs;
using ReservationApp.ViewModels;

namespace ReservationApp.Controllers;

[Authorize]
public class BookingController : Controller
{
    private readonly IVnPayService _vnPayService;
    private readonly IExporter _exporter;
    private readonly IBookingService _bookingService;
    private readonly IVillaNumberService _villaNumberService;
    private readonly IVillaService _villaService;
    private readonly IAmenityService _amenityService;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IEmailService _emailService;
    private readonly IOwnerBalanceService _ownerBalanceService;
    private readonly IOwnerSettlementService _ownerSettlementService;
    private readonly IHubContext<DashBoardHub> _hubContext;
    private readonly IQRCoderService _qrCodeService;
    public BookingController(IVnPayService vnPayService, IExporter exporter,
        IBookingService bookingService, IVillaNumberService villaNumberService, IVillaService villaService,
        IAmenityService amenityService,
        UserManager<ApplicationUser> userManager, IEmailService emailService,
        IOwnerBalanceService ownerBalanceService, IHubContext<DashBoardHub> hubContext,
        IOwnerSettlementService ownerSettlementService, IQRCoderService qrCodeService
        )
    {
        _vnPayService = vnPayService;
        _exporter = exporter;
        _bookingService = bookingService;
        _villaNumberService = villaNumberService;
        _villaService = villaService;
        _amenityService = amenityService;
        _userManager = userManager;
        _emailService = emailService;
        _ownerBalanceService = ownerBalanceService;
        _hubContext = hubContext;
        _ownerSettlementService = ownerSettlementService;
        _qrCodeService = qrCodeService;

    }

    public IActionResult Index()
    {
        return View();   
    }
    
    public IActionResult FinalizeBooking(int VillaId, string checkInDate, int Nights)
    {
        if (!DateOnly.TryParseExact(checkInDate, "dd/MM/yyyy", null, System.Globalization.DateTimeStyles.None, out var parsedDate))
        {
            ModelState.AddModelError("CheckInDate", "Invalid date format. Please use dd/MM/yyyy.");
            return BadRequest("Invalid date format.");
        }
        
        
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
        
        ApplicationUser user = _userManager.FindByIdAsync(userId).Result;
        var villa = _villaService.GetById(VillaId, "Amenities");
        var bookings = _bookingService.GetAll(x => x.VillaId == VillaId).ToList();
        var villaNumbers = _villaNumberService.GetAll(x => x.Villa.Id == VillaId).ToList();
        var roomAvailable = SD.VillaRoomsAvailable_Count(VillaId,villaNumbers, DateOnly.Parse(  checkInDate), Nights, bookings);
        Booking booking = new Booking()
        {
            VillaId = VillaId,
            CheckInDate = parsedDate,
            Nights = Nights,
            CheckOutDate = parsedDate.AddDays(Nights),
            Villa = villa,
            TotalCost = villa.Price * Nights,
            UserId = userId,
            Name = user.Name,
            Email = user.Email,
            Phone = user.PhoneNumber,
            VillaNumbers = roomAvailable.ToList(),
            
        };
        return View(booking);
    }

    public IActionResult BookingDetails(int bookingId)
    {
        var bookingFromDB = _bookingService.GetById(x => x.Id == bookingId, "User,Villa");
        bookingFromDB.Villa.Amenities = _amenityService.GetAll(x => x.VillaId == bookingFromDB.VillaId);

        if (bookingFromDB.Status == SD.StatusApproved || bookingFromDB.Status == SD.StatusCompleted || bookingFromDB.Status == SD.StatusCheckedIn)
        {
            var availableVillaNumber = AssignVillaNumber(bookingFromDB.VillaId);
            bookingFromDB.VillaNumbers = availableVillaNumber;
        } 
        return View(bookingFromDB);   
    }
    [HttpPost]
    public IActionResult FinalizeBooking(Booking booking, string paymentMethod)
    {
        try
        {
            //lock resource and add booking 
            _bookingService.Add(booking, paymentMethod);
            if (!booking.IsPaidAtCheckIn)
            {
                return RedirectToAction(nameof(CreatePaymentUrlVnpay), new { bookingId = booking.Id });
            }

            return RedirectToAction(nameof(BookingConfirmation), new { bookingId = booking.Id });
        }
        catch (Exception ex)
        {
            TempData["Error"] = ex.Message;
            return RedirectToAction("Index", "Home");
        }
        

    }
    public IActionResult CreatePaymentUrlVnpay(int bookingId)
    {
        var booking = _bookingService.GetById(x => x.Id == bookingId, "Villa");

        var model = new PaymentInformationModel
        {
            Amount = booking.TotalCost,
            Name = booking.Email,
            OrderDescription = $"{booking.Id}",
            OrderType = "booking",
        };

        var url = _vnPayService.CreatePaymentUrl(model, HttpContext);
        return Redirect(url);
    }

    [HttpGet]
    public IActionResult PaymentCallbackVnpay()
    {
        var response = _vnPayService.PaymentExecute(Request.Query);
        if (response.VnPayResponseCode == "00")
        {
            var value   = response.OrderDescription.Split(" ");
            var customerEmail = value[0];
            // get bookingID
            var bookingId = int.Parse(value[1]);
            var booking = _bookingService.GetById(x => x.Id == bookingId);
            var villa = _villaService.GetById(booking.VillaId);
            
            //update booking after payment successfully
            _bookingService.UpdateStatus(bookingId, SD.StatusApproved);
            _bookingService.UpdatePaymentId(bookingId, response.PaymentId);
            
            // add checkinToken for scan QR 
            _bookingService.CreateCheckInToken(bookingId);
            
            
            //sending notification that booking successfully through email 
            // _emailService.configMailPaySuccess(customerEmail, villa.Name, booking.VillaNumber);
            
            _hubContext.Clients.All.SendAsync("NewBooking", new { booking.Id});
            return View(nameof(BookingConfirmation), bookingId);
        }
        return RedirectToAction("Error","Home");
    }

    [HttpGet]
    [Route("qrcode")]
    public IActionResult GetQRCode([FromQuery]string checkInToken)
    {
        var qrcode = _qrCodeService.GenerateQRCode(checkInToken);
        return File(qrcode, "image/png");
    }

    // [HttpGet]
    // [AllowAnonymous]
    // public IActionResult ScanQR()
    // {
    //     return View();   
    // }
    [HttpPost]
    [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Owner}")]
    public IActionResult CheckinByQR([FromBody] QRCheckinDto dto)
    {
        var booking = _bookingService.CheckQRCodeVallid(dto.BookingId, dto.CheckinToken);
        if (booking is not null)
        {
            _bookingService.UpdateStatus(dto.BookingId, SD.StatusCheckedIn);
            _hubContext.Clients.All.SendAsync("RevenueChange", new { dto.BookingId, booking.VillaNumber });
            _ownerBalanceService.UpdateBalance(dto.BookingId);

            return Json(new
            {
                success = true,
                redirectUrl = Url.Action(nameof(BookingDetails), new { bookingId = booking.Id })
            });
        }

        return BadRequest(new { success = false, message = "Invalid QR code" });
    }

    public IActionResult BookingConfirmation(int bookingid )
    {
        return View(bookingid);
    }

    private List<int> AssignVillaNumber(int villaId)
    {
        List<int> availableVillaNumber = new List<int>();
        var villaNumbers = _villaNumberService.GetAll(u => u.Villa.Id == villaId);
        var checkedInVillaNumber = _bookingService.GetAll(u => u.Villa.Id == villaId 
        && u.Status == SD.StatusCheckedIn).Select(u => u.VillaNumber).ToList();
        foreach (var villaNumber in villaNumbers)
        {
            if (!checkedInVillaNumber.Contains(villaNumber.Villa_Number))
            {
                availableVillaNumber.Add(villaNumber.Villa_Number);
            }
        }

        return availableVillaNumber;

    }
    [HttpPost]
    [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Owner}")]
    public IActionResult CheckIn(Booking booking)
    {
        _bookingService.UpdateStatus(booking.Id, SD.StatusCheckedIn);
        // update ownerbalance when customer using payment online method 
        _ownerBalanceService.UpdateBalance(booking.Id);
        _hubContext.Clients.All.SendAsync("RevenueChange", new { booking.Id, booking.VillaNumber });
        // update owner settlement when booking is paid onsite
        _ownerSettlementService.Create(booking);
        TempData["Success"] = "Booking is checked in successfully";
        return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
    }
    [HttpPost]
    [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Owner}")]
    public IActionResult CheckOut(Booking booking)
    {
        _bookingService.UpdateStatus(booking.Id, SD.StatusCompleted);
        //send notification booking complete
        _hubContext.Clients.Group(SD.Role_Owner).SendAsync("BookingComplete", new { booking.Id });
        TempData["Success"] = "Booking is checked out successfully";
        return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
    }
    [HttpPost]

ReservationApp.Web/Controllers/RatingController.cs
using Microsoft.AspNetCore.Mvc;
using ReservationApp.Application.Services.interfaces;
using ReservationApp.ViewModels;

namespace ReservationApp.Controllers;

public class RatingController : Controller
{
    private readonly IRatingService _ratingService;

    public RatingController(IRatingService ratingService)
    {
        _ratingService = ratingService;       
    }
    [HttpPost]
    public IActionResult Create([FromBody] RatingRequestDTO ratingRequest)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);       
        }
        _ratingService.Add(ratingRequest);       
        return Ok(new { message = "Rating received successfully!" });
    }
    [HttpGet]
    public IActionResult GetRatingsByVillaId([FromQuery]int villaId)
    {
        var ratings = _ratingService.GetAll(u => u.VillaId == villaId);
        return Ok(ratings);       
    }
}

ReservationApp.Web/Controllers/VillaController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ReservationApp.Application.Common.Interfaces;
using ReservationApp.Application.Common.utility;
using ReservationApp.Application.Services.interfaces;
using ReservationApp.Domain.Entities;
namespace ReservationApp.Controllers;

[Authorize]
public class VillaController : Controller
{
    
    private readonly IVillaService _villaService;
    public VillaController(IVillaService villaService)
    {
        _villaService = villaService;
    }
    // GET
    public IActionResult Index()
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var role = claimIdentity.FindFirst(ClaimTypes.Role).Value;
        var email = claimIdentity.FindFirst(ClaimTypes.Name).Value;
        if (role == SD.Role_Owner)
        {
            return View(_villaService.GetAll(x=> x.OwnerEmail == email));
        }
        return View(_villaService.GetAll());
    }

    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Create(Villa obj)
    {
        var claimIdentity = (ClaimsIdentity)User.Identity;
        var email = claimIdentity.FindFirst(ClaimTypes.Email).Value;
        obj.OwnerEmail = email;
        if (!_villaService.Add(obj, out string errorMessage))
        {
            if(errorMessage == "Name and Description cannot be the same")
            {
                ModelState.AddModelError("Description", "Name and Description cannot be the same");
            }
            return View(obj);
        }
        
        TempData["Success"] = "Villa created successfully";
        return RedirectToAction(nameof(Index));
    }
    public IActionResult Update(int villaId)
    {
        var villa = _villaService.GetById(villaId);
        if (villa is null)
        {
            return RedirectToAction("Error", "Home");
        }
        return View(villa);
    }
    [HttpPost]
    public IActionResult Update(Villa obj)
    {
        if (ModelState.IsValid && obj.Id > 0)
        {
            _villaService.Update(obj);
            TempData["Success"] = "Villa updated successfully";
            return RedirectToAction(nameof(Index));
        } 
        TempData["Error"] = "Villa updated failure";
        return View(obj);
    }
    public IActionResult Delete(int villaId)
    {
        var villa = _villaService.GetById(villaId);
        if (villa is null)
        {
            TempData["Error"] = "Villa not found";
            return RedirectToAction("Error", "Home");
        }
        return View(villa);
    }
    [HttpPost]
    public IActionResult Delete(Villa obj)
    {
        if (_villaService.Delete(obj, out string errorMessage))
        {
            TempData["Success"] = "Villa deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        TempData["Error"] = errorMessage;
        return RedirectToAction("Error", "Home");
    }
}

ReservationApp.Web/Views/Shared/_CityDropDown.cshtml
@model Villa  
<div class="py-1 col-12">
    <label asp-for="City" class="form-label ms-2">Select a province/city:</label>
    <select asp-for="City" id="province" class="form-control border shadow">
        <option>Đang tải...</option>
    </select>
    <span asp-validation-for="City" class="text-danger"></span>
</div>

ReservationApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationApp.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/ReservationApp.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/apexcharts.css" />
    <link href="~/css/rating.css" rel="stylesheet"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow ">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" width="35px"/></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Content management
                        </a>
                        <ul class="dropdown-menu">
                            @if (User.IsInRole(SD.Role_Admin))
                            {
                                <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Villa</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="Index">Villa numbers</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Amenity" asp-action="Index">Amenity</a></li>
                            }
                            <li><a class="dropdown-item" asp-area="" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">Booking</a></li>

                        </ul>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="">
    <main role="main" class="">
        <div class = "loading spinner" style = "display:none">
            Loading...
        </div>
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted bg-dark">
    <div class="container text-center">
        Create by Dat9999999 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-code-slash" viewBox="0 0 16 16">
            <path d="M10.478 1.647a.5.5 0 1 0-.956-.294l-4 13a.5.5 0 0 0 .956.294zM4.854 4.146a.5.5 0 0 1 0 .708L1.707 8l3.147 3.146a.5.5 0 0 1-.708.708l-3.5-3.5a.5.5 0 0 1 0-.708l3.5-3.5a.5.5 0 0 1 .708 0m6.292 0a.5.5 0 0 0 0 .708L14.293 8l-3.147 3.146a.5.5 0 0 0 .708.708l3.5-3.5a.5.5 0 0 0 0-.708l-3.5-3.5a.5.5 0 0 0-.708 0"/>
        </svg>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="/js/JSGlobalConst.js"></script>
<script src="~/js/rating.js"></script>
<script src="~/js/CityAPi.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
@*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
<script src="~/js/apexcharts.js"></script>
<script src="~/js/formatNumber.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ReservationApp.Web/Views/Shared/_LoginPartialAdmin.cshtml
@inject UserManager<ApplicationUser> UserManager


<ul class="navbar-nav  d-none d-md-flex nav-login">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
           data-bs-toggle="dropdown" aria-expanded="false">
            Hello @UserManager.GetUserName(User)
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-center" asp-controller="Account" asp-action="Logout">Logout</a>
        </ul>
    </li>
</ul>

ReservationApp.Web/Views/Shared/_VillasList.cshtml
@model HomeVM
<div class="row px-lg-5 m-lg-4 m-sm-0 px-sm-0" style="--bs-gutter-x:0">
@if (Model.VillaList != null && Model.VillaList.Any())
{
    @foreach (var villa in @Model.VillaList)
    {
        <div class="p-4 col-md-12 col-lg-6">
            <div class="row" style="border-radius:5px; border: 1px solid #aaa">
                <div class="col-4 p-2">
                    <img class="d-block w-100" style="border-radius:5px;" src="@villa.ImageUrl">
                </div>
                <div class="col-8">
                    <div class="d-flex justify-content-between">
                        <p class="card-title text-warning" style="font-size:xx-large">@villa.Name</p>
                        <div class="pt-2">
                            <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target='#exampleModal-@(villa.Id)'>
                                Details
                            </button>
                        </div>
                    </div>
                    <p class="card-text">
                        @villa.Description
                    </p>
                </div>
                <div class="col-12">
                    <div class="row pb-3 pt-2">
                        <div class="col-4">
                            @if (Model.CheckInDate > DateOnly.FromDateTime(DateTime.Now))
                            {
                                if (villa.IsAvaliable)
                                {
                                    <a asp-controller="Booking" asp-action="FinalizeBooking" asp-route-VillaId="@villa.Id"
                                       asp-route-checkInDate="@Model.CheckInDate.ToString("dd/MM/yyyy")"
                                       asp-route-Nights="@Model.Nights"
                                       class="btn btn-success form-control btn-block">
                                        Book
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-outline-danger disabled form-control btn-block">
                                        Sold Out
                                    </a>
                                }
                            }
                        </div>
                        <div class="col-4">
                            <span class="">Max Occupancy : @villa.Occupancy adults </span><br/>
                            <span class=" pt-1">Villa Size : @villa.Sqft</span><br/>
                        </div>
                        <div class="col-4">
                            <span class="text-warning float-end font-weight-bold pt-1" style="font-size:25px;">

                                <span style="border-bottom:1px solid #ff6a00">
                                    @villa.Price.ToString("C")
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="modal fade" id="exampleModal-@(villa.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl" style="border: 1px solid #aaa; border-radius:7px;">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-3 text-success" id="exampleModalLabel">Villa Details</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body m-0">
                        <partial name="_villaDetails" model="@villa"/>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>
    }
}
else
{
    <div class="alert alert-warning text-center fw-bold mt-4">
        No villas were found matching your search criteria.
    </div>
}
</div>